allowBuilds:
  '@prisma/engines': true
  bcrypt: true
  prisma: true
  sharp: true
  unrs-resolver: true

overrides:
  tar: ^7.5.11
  minimatch: ^9.0.7
  prismjs: ^1.30.0
  '@hono/node-server': ^1.19.13
  postcss: ^8.5.15
